{{- if .Values.secretFiles.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-monitor.fullname" . }}-secret-files
  labels:
    {{- include "llm-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretFiles.data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.secretFiles.data .Values.certFiles.data }}
---
{{- end }}
{{- if .Values.certFiles.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-monitor.fullname" . }}-cert-files
  labels:
    {{- include "llm-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.certFiles.data }}
  {{ $key }}: |-
{{ $value | indent 4 }}
  {{- end }}
{{- end }}
